name: $(Date:yyyy-MM-dd)$(Rev:_r)

pool:
  vmImage: windows-latest

pr:
  branches:
    include:
      - develop
      - feature/*

trigger:
  branches:
    include:
      - main
      - develop

variables:
  - group: Shared Secrets

steps:
  - task: UseDotNet@2
    displayName: use netcoreapp3.1 sdk
    inputs:
      version: '3.1.x'
      performMultiLevelLookup: true

  - task: UseDotNet@2
    displayName: use net5.0 sdk
    inputs:
      version: '5.0.x'
      performMultiLevelLookup: true

  - task: UseDotNet@2
    displayName: use net6.0 sdk
    inputs:
      version: '6.0.x'

  - task: DotNetCoreCLI@2
    displayName: restore dependencies
    inputs:
      command: restore
      projects: src/**/*.csproj
      feedsToUse: select
      vstsFeed: "4053202a-1650-47d7-804a-73158b8e55f7"

  - task: DotNetCoreCLI@2
    displayName: build projects
    inputs:
      projects: src/**/*.csproj
      arguments: --no-restore

  - task: DotNetCoreCLI@2
    displayName: create packages
    inputs:
      command: pack
      packagesToPack: src/**/*.csproj;!src/**/*.Tests.csproj
      nobuild: true
      includesymbols: false

  - task: PublishBuildArtifacts@1
    displayName: publish artifact
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: xperience-static-web-assets-storage
    condition: succeededOrFailed()
